import type { ThemeConfig } from "antd";

export const components = {
  Button: {
    defaultShadow: "0",
    dangerShadow: "0",
    lineWidth: 2,
    algorithm: true,
    borderColorDisabled: "rgb(232,233,245)",
    defaultGhostColor: "rgb(103,63,105)",
    defaultGhostBorderColor: "rgb(103,63,105)",
    primaryShadow: "0",
    paddingInlineSM: 16,
    paddingInline: 24,
    paddingInlineLG: 32,
    borderRadius: 16,
    borderRadiusLG: 20,
    borderRadiusSM: 14,
    fontSizeSM: 12,
    fontSize: 14,
    fontSizeLG: 16,
    fontWeight: 500,
    controlHeightLG: 48,
    controlHeight: 40,
    controlHeightSM: 32,
  },
  Typography: {
    colorTextHeading: "#673f69",
    fontSizeHeading1: 60,
    fontSizeHeading2: 48,
    fontSizeHeading3: 40,
    fontSizeHeading4: 32,
    fontSizeHeading5: 24,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.2,
    lineHeightHeading3: 1.2,
    lineHeightHeading4: 1.2,
    lineHeightHeading5: 1.2,
  },
  Breadcrumb: {
    separatorMargin: 12,
  },
  Dropdown: {
    controlPaddingHorizontal: 16,
    paddingBlock: 8,
  },
  Cascader: {
    lineWidth: 2,
    controlItemWidth: 128,
    menuPadding: 8,
    optionPadding: "8px 16px",
  },
  Input: {
    lineWidth: 2,
    borderRadius: 16,
    borderRadiusLG: 20,
    borderRadiusSM: 14,
    paddingInlineSM: 8,
    paddingInline: 16,
    paddingInlineLG: 24,
    fontWeightStrong: 600,
    controlHeightLG: 48,
    controlHeight: 40,
    controlHeightSM: 32,
  },
  DatePicker: {
    lineWidth: 2,
  },
  InputNumber: {
    lineWidth: 2,
    borderRadius: 16,
    borderRadiusLG: 20,
    borderRadiusSM: 12,
  },
  Mentions: {
    lineWidth: 2,
    controlItemWidth: 256,
    controlPaddingHorizontal: 24,
    borderRadius: 16,
    borderRadiusLG: 20,
    borderRadiusSM: 12,
  },
  Checkbox: {
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    lineWidth: 2,
    lineWidthBold: 2,
    controlInteractiveSize: 18,
  },
  Select: {
    lineWidth: 2,
    borderRadius: 16,
    borderRadiusLG: 20,
    borderRadiusSM: 12,
    borderRadiusXS: 8,
    paddingSM: 16,
    controlPaddingHorizontal: 20,
    controlPaddingHorizontalSM: 12,
    paddingXS: 12,
    optionPadding: "8px 16px",
    fontSizeIcon: 12,
  },
  Slider: {
    handleColor: "rgb(103,63,105)",
    railBg: "rgb(232,233,245)",
    trackBg: "rgb(103,63,105)",
    railSize: 6,
    handleLineWidth: 4,
    handleLineWidthHover: 4,
    trackHoverBg: "rgb(255,175,69)",
    handleActiveColor: "rgb(255,175,69)",
  },
  Transfer: {
    itemPaddingBlock: 8,
    listWidth: 256,
    lineWidth: 2,
  },
  TreeSelect: {
    borderRadius: 16,
    borderRadiusSM: 12,
  },
  Upload: {
    lineWidth: 2,
  },
  Calendar: {
    lineWidth: 2,
  },
  Card: {
    lineWidth: 2,
    borderRadiusLG: 20,
    padding: 0,
    paddingLG: 0,
    boxShadowCard: "0px 0px 24px 0 rgba(103, 63, 105, 0.48)",
    boxShadowTertiary: "4px 4px 16px 0 rgba(0, 0, 0, 0.1)",
  },
  Collapse: {
    borderRadiusLG: 20,
    lineWidth: 2,
  },
  Descriptions: {
    lineWidth: 2,
  },
  List: {
    lineWidth: 2,
    borderRadiusLG: 20,
  },
  Popover: {
    borderRadiusLG: 20,
    borderRadiusXS: 8,
  },
  Segmented: {
    borderRadius: 16,
    borderRadiusLG: 20,
    borderRadiusSM: 12,
    borderRadiusXS: 8,
  },
  Table: {
    borderRadius: 16,
    lineWidth: 2,
  },
  Tabs: {
    lineWidth: 2,
    borderRadius: 16,
    borderRadiusLG: 20,
  },
  Tag: {
    lineWidth: 2,
    borderRadiusSM: 12,
  },
  Tree: {
    borderRadius: 16,
    borderRadiusSM: 12,
    lineWidth: 2,
  },
  Radio: {
    borderRadius: 16,
    borderRadiusLG: 20,
    borderRadiusSM: 12,
    dotSize: 10,
  },
  Alert: {
    lineWidth: 2,
    borderRadiusLG: 20,
    defaultPadding: "8px 16px",
  },
  Drawer: {
    borderRadiusSM: 12,
    lineWidth: 2,
  },
  Message: {
    borderRadiusLG: 20,
    contentPadding: "12px 20px",
  },
  Modal: {
    borderRadiusLG: 20,
    borderRadiusSM: 12,
    lineWidth: 2,
  },
  Notification: {
    borderRadiusLG: 20,
    borderRadiusSM: 12,
    lineWidthFocus: 4,
  },
  Skeleton: {
    borderRadiusSM: 12,
  },
} as ThemeConfig["components"];

export default {
  colorPrimary: "#673f69",
  colorInfo: "#445bcc",
  colorPrimaryBg: "rgba(103, 63, 105, 0.32)",
  colorSuccess: "#55c989",
  colorWarning: "#ffc24d",
  colorError: "#d65952",
  colorTextBase: "#1e1b4b",
  colorBgBase: "#fafbfc",
  fontSize: 16,
  fontSizeXL: 20,
  borderRadius: 12,
  borderRadiusLG: 16,
  borderRadiusSM: 8,
  borderRadiusXS: 4,
  colorLink: "#673f69",
  fontFamily: "var(--quicksand)",
} as ThemeConfig["token"];
