import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      "Credential Error": "Username or password error",
      "Input": "Please enter {{inputMessage}}",
      "InputSpecie": "the specie",
      "InputUsername": "your name",
      "InputSize": "the pet size",
      "InputSex": "the pet sex",
      "InputPetName": "the name the pet responds to",
      "PetDescription": "the description of the pet",
      "PetAge": "the pet age",
      "ContactPhone": "a contact phone",
      "LostAddress": "an approximate address where the pet was lost",
      "PetImages": "some photos of the pet",
    }
  },
  es: {
    translation: {
      "Registered Volunteer": "Voluntario Registrado",
      "Name": "Nombre",
      "Register": "Registrarme",
      "Email": "Correo Electrónico",
      "Contact Phone": "Teléfono de Contácto",
      "Max Volunteers": "Cantidad de Voluntarios",
      "Input campaign image": "Ingresa una imagen de la campaña",
      "Is the campaign active?": "¿La campaña está activa?",
      "Location Address": "Dirección del Lugar",
      "Location": "Lugar",
      "End Date": "Fecha de Finalización",
      "Start Date": "Fecha de Inicio",
      "Title": "Título",
      "Submit pets": "Cargar mascotas",
      "Create Campaign": "Crear Campaña",
      "Add pet": "Agregar mascota",
      "Input pet images": "Ingresa imagenes de la mascota",
      "Input pet description": "Ingresa una descripción de la mascota",
      "Weight": "Peso",
      "Enter the pet weight": "Ingresa el peso del animal",
      "Size": "Tamaño",
      "Select the pet size": "Selecciona el tamaño de la mascota",
      "Enter the pet age": "Ingresa la edad de la mascota",
      "Select pet sex": "Selecciona el sexo de la mascota",
      "Sterilized": "Esterilizado",
      "Vaccinated": "Vacunado",
      "Dewormed": "Desparasitado",
      "Age": "Edad",
      "Identifier": "Identificador",
      "Incorrect credentials": "Usuario o contraseña incorrectos",
      "Password updated": "Contraseña actualizada",
      "Expired token, please generate a new one": "Token expirado, por favor genera uno nuevo",
      "Change password": "Cambiar contraseña",
      "Email Sent": "Correo Enviado",
      "User doesn´t exist": "El usuario no existe",
      "Credential Error": "Usuario o contraseña incorrectos",
      "Lost Address": "Dirección aproximada de pérdida",
      "Contact phone": "Teléfono de contacto",
      "Pet Age": "Edad de la mascota",
      "Description": "Descripción",
      "Contact Name": "Su nombre",
      "Specie": "Especie",
      "Sex": "Sexo",
      "Pet Name": "Nombre de la mascota",
      "Input": "Por favor ingresa {{inputMessage}}",
      "PetImages": "algunas fotos de la mascota",
      "InputSpecie": "la especie",
      "InputUsername": "tu nombre",
      "InputSize": "el tamaño de la mascota",
      "InputSex": "el sexo de la mascota",
      "InputPetName": "el nombre al que responde la mascota",
      "PetDescription": "una descripción de la mascota",
      "PetAge": "la edad de la mascota",
      "ContactPhone": "un teléfono de contácto",
      "LostAddress": "una dirección aproximada donde se perdió la mascota",
      "Canine": "Canino",
      "Feline": "Felino",
      "Bovine": "Bovino",
      "Equine": "Equino",
      "Suidae": "Suidae",
      "Caprinae": "Caprino",
      "Phasianidae": "Fasiánidos",
      "Anatidae": "Ánatidos",
      "Columbidae": "Colúmbidos",
      "Leporidae": "Lepóridos",
      "Numididae": "Numídidos",
      "Odontophoridae": "Odontofóridos",
      "Camelidae": "Camélidos",
      "Male": "Macho",
      "Female": "Hembra",
      "Health": "Salud",
      "Nutrition": "Nutrición",
      "Care": "Cuidado",
      "Behavior": "Comportamiento",
      "Adoption": "Adopción",
      "Beauty": "Belleza",
      "Other": "Otro",
      "Big": "Grande",
      "Medium": "Mediano",
      "Small": "Pequeño",
      "New pets created recently": "Nuevas mascotas cargadas recientemente",
      "¡I want to  see them!": "¡Quiero verlas!",
      "Refresh to see them": "Refrescar para verlas"
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: "es",

  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
